### ISSUE TITLE
tech report: im Output am Blog wird die Organisation nicht angezeigt

### ISSUE THREAD

**Issue by julianaus** [skasberger/crowd-bib#11]
![bildschirmfoto 2014-03-20 um 12 22 09](https://f.cloud.github.com/assets/5329532/2471281/478ab6a6-b022-11e3-9858-98d7b12ec8fc.png)
Siehe screenshot

**Comment by skasberger** [comment]
fixed: commit 727eff900455b4495b8a331313bef6ce2460774f
