### ISSUE TITLE
Conference -> pages hinzufügen

### ISSUE THREAD

**Issue by julianaus** [skasberger/crowd-bib#7]
Die Proceedings haben oft eine Seitennummer, die kann man bei der Konferenz noch nicht hinzufügen. So sollte es am Ende aussehen: 
Weber, W., & Rall, H. (2012). Data Visualization in Online Journalism and Its Implications for the Production Process. In 2012 16th International Conference on Information Visualisation (IV) **(pp. 349–356)**. Montpellier. doi:10.1109/IV.2012.65
[Hervorhebung mit Fett von mir]

**Comment by skasberger** [comment]
fix: commit 1e484626216ab801ddf1d57e8d2c81f74fa58108
