### ISSUE TITLE
conference proceedings werden nicht im output als kategorie angezeigt

### ISSUE THREAD

**Issue by julianaus** [skasberger/crowd-bib#8]
![bildschirmfoto 2014-02-07 um 12 50 07](https://f.cloud.github.com/assets/5329532/2109302/2c8a1e2c-8fee-11e3-83a3-64b17b5862b1.png)

**Comment by skasberger** [comment]
statt (???) müsste conference proceeding stehen.

**Comment by skasberger** [comment]
fix: commit 8a090e6fb9463aa7aa8b4e9d84696d8eb196e811
